# Generated by Django 4.2.9 on 2024-01-05 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=230, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('country_code', models.CharField(choices=[('GB', 'United Kingdom'), ('US', 'United States'), ('IN', 'INDIA')], default='IN', max_length=2)),
            ],
        ),
    ]
